# Arquivo azure-pipelines.yml

trigger:
  branches:
    include:
      - main
pool:
  vmImage: ubuntu-latest

lockBehavior: sequential

stages:
- stage: Build
  jobs:
    - job: BuildAndTest
      displayName: 'Build and Test React App'
      steps:
        - script: echo "Ok"