# Arquivo azure-pipelines.yml

trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: BuildAndTest
    displayName: 'Build and Test React App'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '14.x'
        displayName: 'Instalar Node.js'

  
